=== codepil/eTimber/estate/config/estateSample.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="ClassA" type="xsd:string"/>
    <xsd:element name="ClassB" type="xsd:string"/>
    <xsd:element name="ClassC" type="xsd:string"/>
    <xsd:element name="ClassD" type="xsd:string"/>
    <xsd:element name="Clerk" type="xsd:string"/>
    <xsd:element name="CoupContractor" type="xsd:string"/>
    <xsd:element name="Date" type="xsd:string"/>
    <xsd:element name="DelNo" type="xsd:string"/>
    <xsd:element name="Estate">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="1">
                <xsd:element ref="PlanterName" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="PlantAddress" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="SyNo" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="CoupContractor" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="Incoming">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Estate" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="LoadDetails" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="LoadDetails">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="load"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="Logs" type="xsd:string"/>
    <xsd:element name="LorryNumber" type="xsd:string"/>
    <xsd:element name="PlantAddress" type="xsd:string"/>
    <xsd:element name="PlanterName" type="xsd:string"/>
    <xsd:element name="SNo" type="xsd:string"/>
    <xsd:element name="Stumps" type="xsd:string"/>
    <xsd:element name="SyNo" type="xsd:string"/>
    <xsd:element name="Tape" type="xsd:string"/>
    <xsd:element name="TotalCFT" type="xsd:string"/>
    <xsd:element name="Unload" type="xsd:string"/>
    <xsd:element name="load">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="SNo"/>
                <xsd:element ref="Date"/>
                <xsd:element ref="LorryNumber"/>
                <xsd:element ref="Tape"/>
                <xsd:element ref="Clerk"/>
                <xsd:element ref="Logs"/>
                <xsd:element ref="ClassA"/>
                <xsd:element ref="ClassB"/>
                <xsd:element ref="ClassC"/>
                <xsd:element ref="ClassD"/>
                <xsd:element ref="TotalCFT"/>
                <xsd:element ref="Unload"/>
                <xsd:element ref="DelNo"/>
                <xsd:element ref="Stumps"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== codepil/eTimber/estate/data/Nagaraj/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../config/estateSample-dataLogic.xsl"?>
<Incoming xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="estateSample.xsd">
  <Estate>
    <PlanterName>Nagaraj</PlanterName>
    <PlantAddress></PlantAddress>
    <SyNo></SyNo>
    <CoupContractor></CoupContractor>
    <tcft>37.98</tcft>
    <discount>3</discount>
    <disTcft></disTcft>
  </Estate>
  <LoadDetails>
    <load>
      <SNo>1</SNo>
      <Date>8 Apr 2008</Date>
      <LorryNumber>load1</LorryNumber>
      <Logs>1</Logs>
      <ClassA>12.66</ClassA>
      <ClassB>0.00</ClassB>
      <ClassC>0.00</ClassC>
      <ClassD>0.00</ClassD>
      <TotalCFT>12.66</TotalCFT>
      <Unload>&lt;Unload Place&gt;</Unload>
      <Clerk></Clerk>
      <Tape>&lt;Clerk Name(s)&gt;</Tape>
      <DelNo>&lt;DN#&gt;</DelNo>
      <Stumps>&lt;no of trees&gt;</Stumps>
    </load>
    <load>
      <SNo>2</SNo>
      <Date>8 Apr 2008</Date>
      <LorryNumber>load2</LorryNumber>
      <Logs>1</Logs>
      <ClassA>12.66</ClassA>
      <ClassB>0.00</ClassB>
      <ClassC>0.00</ClassC>
      <ClassD>0.00</ClassD>
      <TotalCFT>12.66</TotalCFT>
      <Unload>&lt;Unload Place&gt;</Unload>
      <Clerk></Clerk>
      <Tape>&lt;Clerk Name(s)&gt;</Tape>
      <DelNo>&lt;DN#&gt;</DelNo>
      <Stumps>&lt;no of trees&gt;</Stumps>
    </load>
    <load>
      <SNo>3</SNo>
      <Date>8 Apr 2008</Date>
      <LorryNumber>load3</LorryNumber>
      <Logs>1</Logs>
      <ClassA>12.66</ClassA>
      <ClassB>0.00</ClassB>
      <ClassC>0.00</ClassC>
      <ClassD>0.00</ClassD>
      <TotalCFT>12.66</TotalCFT>
      <Unload>&lt;Unload Place&gt;</Unload>
      <Clerk></Clerk>
      <Tape>&lt;Clerk Name(s)&gt;</Tape>
      <DelNo>&lt;DN#&gt;</DelNo>
      <Stumps>&lt;no of trees&gt;</Stumps>
    </load>
  </LoadDetails>
</Incoming>
